### ISSUE TITLE
How to document the response?

### ISSUE THREAD

**Issue by chakia** [mhtess/corpus_generics#10]
In the case of the focus experiment, how do we want the response to be documented in exp.data trials? For example if a participant is given the following:
In the underlined statement, what do you think the speaker meant?
(1) that school buses (as opposed to other entities or things) are notorious 
(2) that school buses are notorious (as opposed to having other qualities or performing other actions)?

and selected (1), do we want the documented response as the sentence itself or simply specifying what was in focus ("NP Focus") or something else?

**Comment by mhtess** [comment]
Let's call it `"NP"` or `"VP"`

**Comment by mhtess** [comment]
but in general, err on the side of recording too much data, so you might want to record other things as well...
