### ISSUE TITLE
Stripping terminals

### ISSUE THREAD

**Issue by cfoster0** [mhtess/corpus_generics#8]
Terminal symbols like *-t* and 0 need to be removed. Modifications to Perl script will be necessary.

**Comment by cfoster0** [comment]
I've been attempting a fix, but the Perl script reacts to my changes in unexpected ways.

**Comment by chakia** [comment]
I have run some sed commands on the database and it seems to strip the terminals manually. The few I have run include:
sed -e s/[*]t[*]//g -i swbd.tab
sed -e s/0//g -i swbd.tab
sed -e s/-[0-9]//g -i swbd.tab
sed -e s/[*]//g -i swbd.tab
However, I am still checking for unexpected behavior.

**Comment by chakia** [comment]
sed -e s/[*]t[*]//g -i swbd.tab <- correction of first command.
